import { PROTOCOL } from './internal/protocol.js';

export { createEngine } from './api/engine.js';
export { PixelJSError } from './api/errors.js';
/** Tilemap cell value that draws nothing. */
export const EMPTY_TILE: number = PROTOCOL.emptyTile;
export type {
  AudioState,
  Engine,
  EngineOptions,
  EngineState,
  EngineStats,
  GameCallbacks,
  Graphics,
  ImageOptions,
  ImageResource,
  TilemapResource,
  TilemapOptions,
  TilemapDrawOptions,
  FontResource,
  FontOptions,
  LoadImageOptions,
  Resource,
  TextOptions,
  SoundResource,
  SoundOptions,
  SoundWaveform,
  SoundEffect,
  SoundInstance,
  NoteOptions,
  MusicOptions,
  MusicResource,
  TrackOptions,
  AudioSystem,
  AudioCapabilities,
  Input,
  PointerSnapshot,
  PointerType,
  WheelSnapshot,
  GamepadButton,
  GamepadAxis,
  GamepadSnapshot,
  RendererKind,
  ScalingMode,
  SpriteOptions,
  TextSize,
  AssetKind,
  AssetManifest,
  AssetBundle,
  LoadAssetsOptions,
  CaptureOptions,
  RecordingOptions,
} from './api/types.js';
export const version = '0.0.3';
