import { readFile, writeFile } from 'node:fs/promises';

// Quarter-wave sine table in Q16 for integer sprite rotation. The table is
// data, so every build and browser rotates sprites to the same pixels.
const steps = 1024;
const values = Array.from({ length: steps + 1 }, (_, index) =>
  Math.round(Math.sin((index * Math.PI) / (2 * steps)) * 65536),
);
const rows = [];
for (let index = 0; index < values.length; index += 8)
  rows.push(`    ${values.slice(index, index + 8).join(', ')},`);
const header = [
  '/* Generated by tools/generate-trig.mjs. Do not edit. */',
  '#ifndef PIXELJS_TRIG_DATA_H',
  '#define PIXELJS_TRIG_DATA_H',
  '',
  '#include <stdint.h>',
  '',
  `/* round(sin(k * pi / ${2 * steps}) * 65536) for k = 0..${steps}. */`,
  `static const int32_t px_quarter_sine[${steps + 1}] = {`,
  ...rows,
  '};',
  '',
  '#endif',
  '',
].join('\n');
const path = new URL('../core/src/graphics/trig_data.h', import.meta.url);
if (process.argv.includes('--check')) {
  const actual = await readFile(path, 'utf8').catch(() => '');
  if (actual !== header)
    throw new Error('Generated artifact differs: core/src/graphics/trig_data.h');
  console.log('Trigonometry table matches its generator.');
} else {
  await writeFile(path, header);
  console.log('Trigonometry table generated.');
}
